# Generated by Django 3.0.8 on 2020-07-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20200715_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
